### ISSUE TITLE
Add SubMenus (I have included a working example)

### ISSUE THREAD

**Issue by coderdnewbie** [jjosh102/Blazor.Tailwind.Templates#5]
I took what you have been doing, (which is impressive) and I have added submenus. The working code is here:

https://github.com/coderdnewbie/Tailwind.SimpleBlazorWebAppTemplate

If you want to use the ideas from this then feel free, especially the Sub Menu feature.

**Comment by jjosh102** [comment]
> I took what you have been doing, (which is impressive) and I have added submenus. The working code is here:
> 
> https://github.com/coderdnewbie/Tailwind.SimpleBlazorWebAppTemplate
> 
> If you want to use the ideas from this then feel free, especially the Sub Menu feature.

Thanks for taking interest in this template. I did try checking the link, but it returns a 404. Was this deleted, or is your repo set to private perhaps?

**Comment by coderdnewbie** [comment]
When you click the link it correctly returns a 404 as I have not written those pages yet (basically the code which needs to be fixed is href="subitem1" and href="subitem2" to the correct pages). This was just a demo that sub menus work. I am hoping your repo will be able to show the technique to more of the community. The code is just my test rig of ideas. With your starter code, the whole this is now pure tailwind (but I have versions with bootstrap 5, Havit, and Fluent UI). 

The code for submenus is not mine, but bootstrap 5 code I found a while ago. My contribution is converting the code from bootstrap 5 to pure tailwind. The next step is to convert the submenu code into components, which I will attempt sometime in the future.

What you have done is good work, you should be happy with what you have done.
