### ISSUE TITLE
Add Submenus (2nd attempt)

### ISSUE THREAD

**Issue by coderdnewbie** [jjosh102/Blazor.Tailwind.Templates#6]
I apologize for messing up my Repo before, I had it on internal. Anyway I have created a new Repo which is public facing. It is here:

https://github.com/coderdnewbie/TailwindDemo

It will show you an easy way to implement submenus. You can improve this and add this to your code.

Thanks.

**Comment by jjosh102** [comment]
Thanks, I 'll look into it.

**Comment by coderdnewbie** [comment]
I have pushed a new version of the code, with a fix for 'TailwindIntegration.targets' as relative paths can be used rather than absolute paths which solves path issues I was getting.
